Student Performance Analysis

In [3]:
from google.colab import files

# This will open a file picker to upload your dataset
uploaded = files.upload()

Saving Student_data.csv to Student_data.csv

In [6]:
#using pandas and numpy

import pandas as pd
import numpy as np

#loading the dataset

df = pd.read_csv("Student_data.csv")

print("STUDENT PERFORMANCE ANALYSIS")
print("=" * 50)

STUDENT PERFORMANCE ANALYSIS
==================================================

In [8]:
#Displaying the data

print("\n1. COMPLETE STUDENT DATA")
display(df)

print("\n2. FIRST FIVE RECORDS")
display(df.head())

print("\n3. COLUMN NAMES")
print(df.columns.tolist())

print("\n4. NUMBER OF ROWS AND COLUMNS")
print(df.shape)

1. COMPLETE STUDENT DATA

,Student_Id,Name,SQL,Python,Artificial Intelligence,Big Data Analytics,Data Structures,Attendance
0,2000,Yashna,85,98,78,88,93,93
1,2001,Sai,92,96,82,78,94,96
2,2002,Rashmitha,38,65,95,89,83,65
3,2003,Suman,76,99,45,42,77,88
4,2004,Sharadha,88,88,79,81,96,94
5,2005,Uday,67,94,86,91,65,85
6,2006,Vinay,45,85,65,72,36,72
7,2007,Sandhya,90,73,44,39,48,98
8,2008,Vaibhav,65,90,92,94,72,80
9,2009,Vijay,94,82,62,64,56,91
10,2010,Veena,78,58,88,85,73,87
11,2011,Vinitha,42,49,80,68,48,58
12,2012,Jyothi,36,93,75,35,72,95
13,2013,Kalyani,86,85,64,93,52,89
14,2014,Hanishk,54,73,85,75,73,90
15,2015,Deekshitha,79,75,93,80,90,68
16,2016,Ravi,22,55,75,48,48,84
17,2017,Srinivas,58,76,48,72,75,99
18,2018,Harini,97,93,72,96,82,76
19,2019,Sreehan,79,90,96,66,48,82

2. FIRST FIVE RECORDS

,Student_Id,Name,SQL,Python,Artificial Intelligence,Big Data Analytics,Data Structures,Attendance
0,2000,Yashna,85,98,78,88,93,93
1,2001,Sai,92,96,82,78,94,96
2,2002,Rashmitha,38,65,95,89,83,65
3,2003,Suman,76,99,45,42,77,88
4,2004,Sharadha,88,88,79,81,96,94

3. COLUMN NAMES
['Student_Id', 'Name', 'SQL', 'Python', 'Artificial Intelligence', 'Big Data Analytics', 'Data Structures', 'Attendance']

4. NUMBER OF ROWS AND COLUMNS
(20, 8)

In [15]:
student_count = len(df)

student_names = df["Name"].tolist()
student_ids = df["Student_Id"].tolist()

subjects = [
    "SQL",
    "Python",
    "Artificial Intelligence",
    "Big Data Analytics",
    "Data Structures"
]

# Convert subject marks and attendance into numeric data
for column in subjects + ["Attendance"]:
    df[column] = pd.to_numeric(df[column], errors="coerce")

if df.empty:
    raise ValueError("The CSV file contains no student records.")

if df[["Student_Id", "Name"] + subjects + ["Attendance"]].isnull().any().any():
    raise ValueError("Please correct missing or non-numeric required values.")

if df["Student_Id"].duplicated().any():
    raise ValueError("Duplicate student IDs found.")

if not df[subjects].apply(
    lambda column: column.between(0, 100).all()
).all():
    raise ValueError("Subject marks must be between 0 and 100.")

if not df["Attendance"].between(0, 100).all():
    raise ValueError("Attendance must be between 0 and 100.")

print("\nTotal students:", student_count)
print("Student names:", student_names)
print("Student IDs:", student_ids)

Total students: 20
Student names: ['Yashna', 'Sai', 'Rashmitha', 'Suman', 'Sharadha', 'Uday', 'Vinay', 'Sandhya', 'Vaibhav', 'Vijay', 'Veena', 'Vinitha', 'Jyothi', 'Kalyani', 'Hanishk', 'Deekshitha', 'Ravi', 'Srinivas', 'Harini', 'Sreehan']
Student IDs: [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]

In [22]:
df["Total_Marks"] = df.apply(calculate_total, axis=1)

df["Average_Marks"] = df.apply(calculate_average, axis=1)

df["Grade"] = df["Average_Marks"].apply(assign_grade)

# Use a loop to calculate each student's result
results = []

for index, row in df.iterrows():
    result = check_result(row)
    results.append(result)

df["Result"] = results

print("\nPROCESSED STUDENT RESULTS")
print("=" * 50)

display(
    df[[
        "Student_Id",
        "Name",
        "Total_Marks",
        "Average_Marks",
        "Grade",
        "Result",
        "Attendance"
    ]].round(2)
)

PROCESSED STUDENT RESULTS
==================================================

,Student_Id,Name,Total_Marks,Average_Marks,Grade,Result,Attendance
0,2000,Yashna,442,88.4,A,Pass,93
1,2001,Sai,442,88.4,A,Pass,96
2,2002,Rashmitha,370,74.0,B,Fail,65
3,2003,Suman,339,67.8,C,Pass,88
4,2004,Sharadha,432,86.4,A,Pass,94
5,2005,Uday,403,80.6,A,Pass,85
6,2006,Vinay,303,60.6,C,Fail,72
7,2007,Sandhya,294,58.8,D,Fail,98
8,2008,Vaibhav,413,82.6,A,Pass,80
9,2009,Vijay,358,71.6,B,Pass,91
10,2010,Veena,382,76.4,B,Pass,87
11,2011,Vinitha,287,57.4,D,Pass,58
12,2012,Jyothi,311,62.2,C,Fail,95
13,2013,Kalyani,380,76.0,B,Pass,89
14,2014,Hanishk,360,72.0,B,Pass,90
15,2015,Deekshitha,417,83.4,A,Pass,68
16,2016,Ravi,248,49.6,D,Fail,84
17,2017,Srinivas,329,65.8,C,Pass,99
18,2018,Harini,440,88.0,A,Pass,76
19,2019,Sreehan,379,75.8,B,Pass,82

In [23]:
# Convert average marks into a NumPy array
averages = df["Average_Marks"].to_numpy()

overall_average = np.mean(averages)
highest_average = np.max(averages)
lowest_average = np.min(averages)
median_average = np.median(averages)
standard_deviation = np.std(averages)

highest_student = df.loc[df["Average_Marks"].idxmax()]
lowest_student = df.loc[df["Average_Marks"].idxmin()]

print("\nOVERALL CLASS PERFORMANCE")
print("=" * 50)

print("Total students:", student_count)
print(f"Overall class average: {overall_average:.2f}")
print(f"Highest student average: {highest_average:.2f}")
print(f"Lowest student average: {lowest_average:.2f}")
print(f"Median student average: {median_average:.2f}")
print(f"Standard deviation: {standard_deviation:.2f}")

print(
    f"Highest-performing student: {highest_student['Name']} "
    f"({highest_average:.2f})"
)

print(
    f"Lowest-performing student: {lowest_student['Name']} "
    f"({lowest_average:.2f})"
)

OVERALL CLASS PERFORMANCE
==================================================
Total students: 20
Overall class average: 73.29
Highest student average: 88.40
Lowest student average: 49.60
Median student average: 74.90
Standard deviation: 11.20
Highest-performing student: Yashna (88.40)
Lowest-performing student: Ravi (49.60)

In [27]:
#pass or fail analysis

pass_count = int((df["Result"] == "Pass").sum())
fail_count = int((df["Result"] == "Fail").sum())

pass_rate = np.divide(pass_count, student_count) * 100
fail_rate = np.divide(fail_count, student_count) * 100

print("\nPASS AND FAIL ANALYSIS")
print("=" * 50)

print("Students passed:", pass_count)
print("Students failed:", fail_count)
print(f"Pass percentage: {pass_rate:.2f}%")
print(f"Fail percentage: {fail_rate:.2f}%")

print("\nPassed students:")
display(df.loc[df["Result"] == "Pass", ["Student_Id", "Name", "Average_Marks"]])

print("\nFailed students:")
display(df.loc[df["Result"] == "Fail", ["Student_Id", "Name", "Average_Marks"]])

PASS AND FAIL ANALYSIS
==================================================
Students passed: 15
Students failed: 5
Pass percentage: 75.00%
Fail percentage: 25.00%

Passed students:

    Student_Id        Name  Average_Marks
0         2000      Yashna           88.4
1         2001         Sai           88.4
3         2003       Suman           67.8
4         2004    Sharadha           86.4
5         2005        Uday           80.6
8         2008     Vaibhav           82.6
9         2009       Vijay           71.6
10        2010       Veena           76.4
11        2011     Vinitha           57.4
13        2013     Kalyani           76.0
14        2014     Hanishk           72.0
15        2015  Deekshitha           83.4
17        2017    Srinivas           65.8
18        2018      Harini           88.0
19        2019     Sreehan           75.8

Failed students:

    Student_Id       Name  Average_Marks
2         2002  Rashmitha           74.0
6         2006      Vinay           60.6
7         2007    Sandhya           58.8
12        2012     Jyothi           62.2
16        2016       Ravi           49.6

In [25]:
#subject wise average

subject_averages = df[subjects].mean()

print("\nSUBJECT-WISE AVERAGE MARKS")
print("=" * 50)

display(
    subject_averages.rename("Average_Marks").to_frame().round(2)
)

best_subject = subject_averages.idxmax()
lowest_subject = subject_averages.idxmin()

print("Best-performing subject:", best_subject)
print("Lowest-performing subject:", lowest_subject)

SUBJECT-WISE AVERAGE MARKS
==================================================

                         Average_Marks
SQL                              68.55
Python                           80.85
Artificial Intelligence          75.20
Big Data Analytics               72.80
Data Structures                  69.05

Best-performing subject: Python
Lowest-performing subject: SQL

In [26]:
# Use a loop to analyse every subject
for subject in subjects:
    subject_marks = df[subject].to_numpy()

    print(f"\nSubject: {subject}")
    print(f"Average marks: {np.mean(subject_marks):.2f}")
    print(f"Highest marks: {np.max(subject_marks)}")
    print(f"Lowest marks: {np.min(subject_marks)}")

    highest_index = df[subject].idxmax()
    highest_name = df.loc[highest_index, "Name"]

    print(
        f"Top student: {highest_name} "
        f"({df.loc[highest_index, subject]} marks)"
    )

Subject: SQL
Average marks: 68.55
Highest marks: 97
Lowest marks: 22
Top student: Harini (97 marks)

Subject: Python
Average marks: 80.85
Highest marks: 99
Lowest marks: 49
Top student: Suman (99 marks)

Subject: Artificial Intelligence
Average marks: 75.20
Highest marks: 96
Lowest marks: 44
Top student: Sreehan (96 marks)

Subject: Big Data Analytics
Average marks: 72.80
Highest marks: 96
Lowest marks: 35
Top student: Harini (96 marks)

Subject: Data Structures
Average marks: 69.05
Highest marks: 96
Lowest marks: 36
Top student: Sharadha (96 marks)

In [32]:
#grade distribution
grade_distribution = df["Grade"].value_counts().reindex(
    ["A", "B", "C", "D", "F"],
    fill_value=0
)

print("\nGRADE DISTRIBUTION")
print("=" * 50)

display(grade_distribution.rename("Student_Count").to_frame())

#attendance analysis
average_attendance = np.mean(df["Attendance"])

print("\nATTENDANCE ANALYSIS")
print("=" * 50)

print(f"Average attendance: {average_attendance:.2f}%")

# Identify students with attendance below 75%
low_attendance = df[df["Attendance"] < 75]

print("\nStudents with attendance below 75%:")

if low_attendance.empty:
    print("No students have attendance below 75%.")
else:
    display(
        low_attendance[["Student_Id", "Name", "Attendance"]]
    )


#final report

print("\n" + "=" * 50)
print("FINAL STUDENT PERFORMANCE REPORT")
print("=" * 50)

print(f"Total students analysed: {student_count}")
print(f"Overall class average: {overall_average:.2f}")
print(f"Highest average: {highest_average:.2f}")
print(f"Lowest average: {lowest_average:.2f}")
print(f"Best subject: {best_subject}")
print(f"Lowest-performing subject: {lowest_subject}")
print(f"Students passed: {pass_count}")
print(f"Students failed: {fail_count}")
print(f"Pass rate: {pass_rate:.2f}%")
print(f"Average attendance: {average_attendance:.2f}%")

print("\nTop-performing students:")

# Fix: Define top_students by sorting the dataframe by Average_Marks in descending order
top_students = df.sort_values(by="Average_Marks", ascending=False).head(5)

for rank, (_, row) in enumerate(top_students.iterrows(), start=1):
    print(
        f"{rank}. {row["Name"]} - "
        f"Average: {row["Average_Marks"]:.2f}, "
        f"Grade: {row["Grade"]}, "
        f"Result: {row["Result"]}"
    )

GRADE DISTRIBUTION
==================================================

       Student_Count
Grade
A                  7
B                  6
C                  4
D                  3
F                  0

ATTENDANCE ANALYSIS
==================================================
Average attendance: 84.50%

Students with attendance below 75%:

    Student_Id        Name  Attendance
2         2002   Rashmitha          65
6         2006       Vinay          72
11        2011     Vinitha          58
15        2015  Deekshitha          68

==================================================
FINAL STUDENT PERFORMANCE REPORT
==================================================
Total students analysed: 20
Overall class average: 73.29
Highest average: 88.40
Lowest average: 49.60
Best subject: Python
Lowest-performing subject: SQL
Students passed: 15
Students failed: 5
Pass rate: 75.00%
Average attendance: 84.50%

Top-performing students:
1. Yashna - Average: 88.40, Grade: A, Result: Pass
2. Sai - Average: 88.40, Grade: A, Result: Pass
3. Harini - Average: 88.00, Grade: A, Result: Pass
4. Sharadha - Average: 86.40, Grade: A, Result: Pass
5. Deekshitha - Average: 83.40, Grade: A, Result: Pass

In [31]:
#export final results


df.to_csv("Student_Performance_Results.csv", index=False)

subject_averages.rename("Average_Marks").to_csv(
    "Subject_Performance_Analysis.csv"
)

grade_distribution.rename("Student_Count").to_csv(
    "Grade_Distribution.csv"
)

print("\nAnalysis completed successfully.")
print("Output files created:")
print("1. Student_Performance_Results.csv")
print("2. Subject_Performance_Analysis.csv")
print("3. Grade_Distribution.csv")

Analysis completed successfully.
Output files created:
1. Student_Performance_Results.csv
2. Subject_Performance_Analysis.csv
3. Grade_Distribution.csv